<script lang="ts">
  import { defineComponent, inject } from "vue";
  import { getDatabase, onValue, ref, set, update, type Unsubscribe } from "firebase/database";
  import type { Store } from "@/main";

  interface Room {
    host: string,
    name: string,
    videoId: string,
    state: "playing" | "paused",
    time: number,
    rate: number,
  }

  interface Player {
    loadVideoById: (videoId: string) => void,
    getPlayerState: () => PlayerState,
    pauseVideo: () => void,
    seekTo: (seconds: number, allowSeekAhead?: boolean) => void,
    getCurrentTime: () => number,
    playVideo: () => void,
    setPlaybackRate: (suggestedRate: number) => void,
  }

  enum PlayerState {
    UNSTARTED = -1,
    ENDED = 0,
    PLAYING = 1,
    PAUSED = 2,
    BUFFERING = 3,
    VIDEO_CUED = 5,
  }

  interface State {
    room: Room | null,
    autogeneratedMemberKey: string | null,
    unsubscribeOnValue: Unsubscribe | null,
    player: Player | null,
    videoUrlInput: string,
    done: boolean,
  }

  const db = getDatabase()

  export default defineComponent({
    setup() {
      return {
        store: inject('store') as Store,
      }
    },
    data(): State {
      return {
        room: null,
        autogeneratedMemberKey: null,
        unsubscribeOnValue: null,
        player: null,
        videoUrlInput: "",
        done: false,
      }
    },
    computed: {
      roomId() {
        return this.$route.params.id as string
      },
    },
    watch: {
      'roomId': {
        async handler(toId: string, fromId: string, cleanup) {
          if (this.unsubscribeOnValue) this.unsubscribeOnValue()

          console.log(toId, fromId)
          if (fromId) await this.removeUserFromRoom(fromId)
          if (toId) this.onJoinRoom(toId)

          cleanup(() => {
            if (this.unsubscribeOnValue) this.unsubscribeOnValue()
          })
        }
      },
      'room.videoId': {
        handler(videoId: string) {
          console.log("videoId", videoId)
          this.player?.loadVideoById(videoId)
        }
      },
      // 'room.time': {
      //   handler(time) {
      //     console.log("time", time)
      //     this.player.seekTo(time)
      //   }
      // },
      'room.rate': {
        handler(rate: number) {
          console.log("rate", rate)
          this.player?.setPlaybackRate(rate)
        }
      },
      'room.state': {
        handler(state: Room["state"]) {
          if (this.room && this.room.host !== this.store.auth.userId) {
            console.log("state", state)

            if (state === "paused" && this.player?.getPlayerState() !== PlayerState.PAUSED) this.player?.pauseVideo()
            else if (state === "playing") {
              console.log("seeking")
              this.player?.seekTo(this.room.time, true)
              this.player?.playVideo()
            }
          }
        }
      },
    },
    beforeCreate() {
      window.onYouTubeIframeAPIReady = () => {
        this.initYoutube()
      }
    },
    created() {
      this.onJoinRoom(this.roomId)
    },
    mounted() {
      // This code loads the IFrame Player API code asynchronously.
      const tag = document.createElement('script');
      tag.src = "https://www.youtube.com/iframe_api";
      const firstScriptTag = document.getElementsByTagName('script')[0] as HTMLScriptElement;
      firstScriptTag.parentNode!.insertBefore(tag, firstScriptTag);
    },
    methods: {
      async onJoinRoom(roomId: string) {
        await this.addUserToRoom(roomId)
      },
      async addUserToRoom(roomId: string) { // TODO: move to room component
        console.log("roomId", roomId)
        const userRef = ref(db, "users" + `/${this.store.auth.userId}`)

        await update(userRef, {
          room: roomId,
        })

        const roomMembersRef = ref(db, "rooms" + `/${roomId}/members`)

        await update(roomMembersRef, {
          [this.store.auth.userId!]: true,
        })
      },
      async removeUserFromRoom(roomId: string) { // TODO: move to room component
        const userRef = ref(db, "users" + `/${this.store.auth.userId}`)

        await update(userRef, {
          room: null
        })

        const roomMembersRef = ref(db, "rooms" + `/${roomId}/members`)

        await update(roomMembersRef, {
          [this.store.auth.userId!]: false,
        })
      },
      initYoutube() {
        const player = new window.YT!.Player('player', {
          height: '390',
          width: '640',
          videoId: null,
          playerVars: {
            'autoplay': 0,
            'playsinline': 1,
            'enablejsapi': 1,
          },
          events: {
            "onReady": this.onPlayerReady,
            "onStateChange": this.onPlayerStateChange,
            "onPlaybackRateChange": this.onPlayerPlaybackRateChange,
            "onError": (e: any) => console.log("error", e),
          },
        });

        this.player = player
      },
      async onPlayerReady() {
        // await event.target.loadVideoById(this.room.videoId)
        const roomRef = ref(db, `rooms/${this.roomId}`)

        this.unsubscribeOnValue = onValue(roomRef, (snapshot) => {
          const room = snapshot.val()

          console.log("roomchange", room)

          this.room = room
        })
        // event.target.playVideo()
      },
      onPlayerStateChange(event: { data: number }) {
        console.log(event.data)

        if (event.data === PlayerState.BUFFERING) return

        const roomRef = ref(db, "rooms" + `/${this.roomId}`)

        if (event.data === PlayerState.PLAYING) {
          update(roomRef, {
            state: "playing",
            time: this.player?.getCurrentTime()
          })
        } else if (event.data === PlayerState.PAUSED) {
          update(roomRef, {
            state: "paused",
            time: this.player?.getCurrentTime()
          })
        }
        // if (event.data == window["YT"].PlayerState.PLAYING && !this.done) {
        //   setTimeout(this.stopVideo, 6000)
        //   this.done = true
        // }
      },
      onPlayerPlaybackRateChange(event: { data: number }) {
        const roomRef = ref(db, `rooms/${this.roomId}`)

        update(roomRef, {
          rate: event.data,
        })
      },
      async loadVideo() {
        const url = new URL(this.videoUrlInput)
        const urlParams = new URLSearchParams(url.search)

        if (urlParams.has("v")) {
          const videoId = urlParams.get("v")

          const roomVideoIdRef = ref(db, `rooms/${this.roomId}/videoId`)

          await set(roomVideoIdRef, videoId)

          // this.player?.loadVideoById(videoId)
        }
      },
    }
  })
</script>

<template>
  <input v-model="videoUrlInput" placeholder="video url here"/>
  <button @click="loadVideo">Load video</button>
  <div id="player"></div>
  <router-link to="/rooms/4">Go to other Id</router-link>
</template>

<style>

</style>
